<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mohits-MacBook-Pro.local" name="BeforeAfterAnnotation" tests="5" failures="1" timestamp="27 Aug 2017 17:25:01 GMT" time="0.005" errors="0">
  <testcase name="f" time="0.0" classname="com.testNg.BeforeAfterAnnotationExample"/>
  <testcase name="f1" time="0.0" classname="com.testNg.BeforeAfterAnnotationExample"/>
  <testcase name="trySoftAssert1" time="0.0" classname="com.testNg.SoftAssertTryial">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
Check1, Failes Here">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check1, Failes Here
	at com.testNg.SoftAssertTryial.trySoftAssert1(SoftAssertTryial.java:26)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- trySoftAssert1 -->
  <testcase name="testTestNg1" time="0.001" classname="com.testNg.TestSkippingAndPriority">
    <skipped/>
  </testcase> <!-- testTestNg1 -->
  <testcase name="testTestNg0" time="0.0" classname="com.testNg.TestSkippingAndPriority">
    <skipped/>
  </testcase> <!-- testTestNg0 -->
</testsuite> <!-- BeforeAfterAnnotation -->
